sudo: required
language: generic

services:
  - docker      

before_install:
  - docker build -t nickinoz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nickinoz/react-test npm test

after_success:
  - docker build -t nickinoz/multi-client-10-14 ./client
  - docker build -t nickinoz/multi-nginx-10-14 ./nginx
  - docker build -t nickinoz/multi-server-10-14 ./server
  - docker build -t nickinoz/multi-worker-10-14 ./worker
  
  #Log into the docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin    
  #Take the images and push it into docker hub
  - docker push nickinoz/multi-client-10-14
  - docker push nickinoz/multi-nginx-10-14
  - docker push nickinoz/multi-server-10-14
  - docker push nickinoz/multi-worker-10-14
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-938743278080'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
