sudo: required
language: generic

services:
  - docker      

before_install:
  - docker build -t nikcinoz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nickinoz/react-test npm test

after_success:
  - docker build -t nickinoz/multi-client ./client
  - docker build -t nickinoz/multi-nginx ./nginx
  - docker build -t nickinoz/multi-server ./server
  - docker build -t nickinoz/multi-worker ./worker
  
  #Log into the docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin    
  #Take the images and push it into docker hub
  - docker push nickinoz/multi-client
  - docker push nickinoz/multi-nginx
  - docker push nickinoz/multi-server
  - docker push nickinoz/multi-worker

